alias obsidian='"/opt/Obsidian/obsidian" > /dev/null 2>&1 & '
alias dbeaver='"/usr/share/dbeaver-ce/dbeaver" > /dev/null 2>&1 & '
alias filezilla='/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=filezilla org.filezillaproject.Filezilla > /dev/null 2>&1 &'
alias chrome1='chromium --args --profile-directory="Profile 1" > /dev/null 2>&1 &'
alias chrome2='chromium --args --profile-directory="Profile 2" > /dev/null 2>&1 &'
